=== CrmPrograming/PrimeroDAM/TrimestreTercero/LND/XML/ejercicio1/ejercicio1.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT factura (alumno, datos_empresa, datos_cliente, datos_factura)>
		<!ELEMENT alumno (#PCDATA)>
		<!ELEMENT datos_empresa (nombre, dir, poblacion, provincia, cif, telefono)>
			<!ELEMENT nombre (#PCDATA)>
			<!ELEMENT dir (#PCDATA)>
			<!ELEMENT poblacion (#PCDATA)>
			<!ELEMENT provincia (#PCDATA)>
			<!ELEMENT cif (#PCDATA)>
			<!ELEMENT telefono (#PCDATA)>
		<!ELEMENT datos_cliente (nombre, dir_env, poblacion, provincia)>
			<!ELEMENT dir_env (#PCDATA)>
		<!ELEMENT datos_factura (fecha, linea+, base, cuota_igic, total)>
			<!ELEMENT fecha (#PCDATA)>
			<!ELEMENT linea (ref, desc, cant, precio, importe)>
				<!ELEMENT ref (#PCDATA)>
				<!ELEMENT desc (#PCDATA)>
				<!ELEMENT cant (#PCDATA)>
				<!ELEMENT precio (#PCDATA)>
				<!ELEMENT importe (#PCDATA)>
			<!ELEMENT base (#PCDATA)>
			<!ELEMENT cuota_igic (#PCDATA)>
			<!ELEMENT total (#PCDATA)>

	<!ATTLIST factura n_fac CDATA #REQUIRED>
	<!ATTLIST poblacion cod_postal CDATA #REQUIRED>
	<!ATTLIST datos_cliente n_cli CDATA #REQUIRED>
	<!ATTLIST datos_factura n_ped CDATA #REQUIRED>
	<!ATTLIST datos_factura igi CDATA #REQUIRED>
	<!ATTLIST datos_factura f_pago (efectivo|tarjeta) #REQUIRED>
	<!ATTLIST datos_factura moneda CDATA #REQUIRED>

=== CrmPrograming/PrimeroDAM/TrimestreTercero/LND/XML/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE factura SYSTEM "ejercicio1.dtd">
<factura n_fac="f123">
	<!-- Añadido el elemento "alumno" con el nombre y apellidos -->
	<alumno>César Ravelo Martínez</alumno>
	<!-- Datos empresa -->
	<datos_empresa>
		<nombre>IES Domingo Pérez Minik</nombre>
		<dir>Curva de Gracia</dir>
		<poblacion cod_postal="38043">San Cristóbal de La Laguna</poblacion>
		<provincia>S/C de Tenerife</provincia>
		<cif>S 3511001-D</cif>
		<telefono>922631444</telefono>
	</datos_empresa>
	<!-- Datos cliente -->
	<datos_cliente n_cli="c879">
		<nombre>Darío, Gutiérrez</nombre>
		<dir_env>Avda. Los Menceyes nº7 1ºd</dir_env>
		<poblacion cod_postal="38123">Santa Cruz de Tenerife</poblacion>
		<provincia>Santa Cruz de Tenerife</provincia>
	</datos_cliente>
	<!-- Datos Factura -->
	<datos_factura n_ped="p731" igi="7" f_pago="efectivo" moneda="euro">
		<fecha>04-04-2017</fecha>
		<!-- Línea 1 -->
		<linea>
			<ref>MII93000F/8</ref>
			<desc>MICRO AMD QUAD-CORE</desc>
			<cant>1</cant>
			<precio>230</precio>
			<importe>266,80</importe>
		</linea>
		<!-- Línea 2 -->
		<linea>
			<ref>MB8QDIA4</ref>
			<desc>PLACA BASE QDI AMD A4</desc>
			<cant>1</cant>
			<precio>180</precio>
			<importe>208,80</importe>
		</linea>
		<!-- Línea 3 -->
		<linea>
			<ref>MEDDR34G</ref>
			<desc>DIMM DDR3 4Gb</desc>
			<cant>2</cant>
			<precio>40</precio>
			<importe>92.80</importe>
		</linea>
		<!-- Línea 4 -->
		<linea>
			<ref>HD500GSA7</ref>
			<desc>DISCO DURO 500GB HDD</desc>
			<cant>4</cant>
			<precio>120</precio>
			<importe>556,80</importe>
		</linea>
		<base>970,00</base>
		<cuota_igic>155,20</cuota_igic>
		<total>1125,20</total>
	</datos_factura>
</factura>
